[package]
name = "sqrite"
version = "0.1.0"
authors = ["makanai5610 <takumi.k.5610@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
